version: "3"

services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: strapi_v4_app
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - DATABASE_CLIENT=postgres
      - DATABASE_HOST=strapiDB
      - DATABASE_PORT=5432
      - DATABASE_NAME=strapi
      - DATABASE_USERNAME=strapi
      - DATABASE_PASSWORD=strapi
    ports:
      - 1337:1337
    volumes:
      - ./config:/opt/app/config
      - ./src:/opt/app/src
      - ./package.json:/opt/package.json
      - ./yarn.lock:/opt/yarn.lock
      - ./.env:/opt/app/.env
      - ./public/uploads:/opt/app/public/uploads
    ports:
      - '1337:1337'
    depends_on:
      - strapiDB
    networks:
      - strapi

  strapiDB:
    container_name: postgres
    image: postgres
    restart: always
    volumes:
      - strapi-data:/var/lib/POSTGRESS
    environment:
      POSTGRES_USER: strapi
      POSTGRES_PASSWORD: strapi
      POSTGRES_DB: strapi
    ports:
      - '3306:3306'
    networks:
      - strapi

volumes:
  strapi-data:
networks:
  strapi:
    name: Strapi
    driver: bridge
