version: "3"

services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: strapi_v4_app
    restart: unless-stopped
    env_file: .env
    environment:
      - NODE_ENV=production
      - DATABASE_CLIENT=postgres
      - DATABASE_HOST=strapiDB
      - DATABASE_PORT=5432
      - DATABASE_NAME=strapi
      - DATABASE_USERNAME=strapi
      - APP_KEYS=dp/z0LDgUjaICZP1F9N5TA==,Bewx0gzksa3PpDVbrMk7xw==,8vDM/VhtrYwRMwve4maPvA==,8fwYXa4/euLViJ49T5PvwA==
      - DATABASE_PASSWORD=strapi
    ports:
      - 1337:1337
    volumes:
      - type: bind
        source: /mnt/strapiConsitentData/docker/app
        target: /srv/app
    ports:
      - '1337:1337'
    depends_on:
      - strapiDB
    networks:
      - strapi

  strapiDB:
    container_name: postgres
    image: postgres
    restart: always
    volumes: 
      - type: bind
        source: /mnt/strapiConsitentData/docker/postgres:/opt/app/postgres
        target: /opt/app/postgres
    environment:
      POSTGRES_USER: strapi
      POSTGRES_PASSWORD: strapi
      POSTGRES_DB: strapi
    ports:
      - '3306:3306'
    networks:
      - strapi

networks:
  strapi:
    name: Strapi
    driver: bridge